### ISSUE TITLE
Consider switching to unicode escape for triangle arrows

### ISSUE THREAD

**Issue by ecbftw** [rstacruz/details-polyfill#1]
Hi there.  Thanks for creating this polyfill.  Just the kind of minimalist implementation I was looking for.

However, I'm having a problem with it under Firefox in Linux.  The triangle arrows show up as gibberish. I was able to fix it by changing these lines:

```
'html.no-details ' + DETAILS + ' > ' + SUMMARY + ':before { content: "▶"; display: inline-block; font-size: .8em; width: 1.5em; }\n' +
'html.no-details ' + DETAILS + '[open] > ' + SUMMARY + ':before { content: "▼"; }')
```

to this:

```
'html.no-details ' + DETAILS + ' > ' + SUMMARY + ':before { content: "\u25b6"; display: inline-block; font-size: .8em; width: 1.5em; }\n' +
'html.no-details ' + DETAILS + '[open] > ' + SUMMARY + ':before { content: "\u25bc"; }')
```

Works great for me in Chrome as well.  Not sure how it looks in IE/Edge.

**Comment by rstacruz** [comment]
Happy to merge it in if anyone sends in a pr. Great detective work :)

**Comment by ecbftw** [comment]
To me personally, a pull request seems like a lot of work for 2 lines of code. ;-P  Note that I'm not a fan of git.
