### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RinkAttendant6** [rstacruz/details-polyfill#9]
In the README and package.json it says MIT but it would be nice to have a LICENSE or LICENSE.md file so that it is detected by GitHub automatically (see https://help.github.com/articles/adding-a-license-to-a-repository/)

Also I wanted to say thanks for creating this polyfill! `<details>` is still "under consideration" in Edge so it's really useful regardless of whether IE support is necessary.

**Comment by rstacruz** [comment]
Thanks! Just added it.
